version: '3.8'

services:

  Yii2SecurityTxt:
    build:
      context: .
      dockerfile: docker/Yii2SecurityTxt/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.1}
    image: rhertogh/yii2-securitytxt-php${PHP_VERSION:-8.1}
    networks:
      - Yii2SecurityTxt
    ports:
      - '${DOCKER_HOST_HTTP_PORT:-80}:80' # http port mapping
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - .:/app
    environment:
      # Yii2
      - YII_ENV=${YII_ENV:-dev}
      # PHP & Xdebug
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG:-serverName=Yii2SecurityTxt}
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG:-1}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      # Yii2 security.txt
      - YII2_SECURITY_TXT_PGP_PRIVATE_KEY=${YII2_SECURITY_TXT_PGP_PRIVATE_KEY:?err}
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  Yii2SecurityTxt:
    driver: bridge
    name: Yii2SecurityTxt
