name: Snyk  Docker Container Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '50 7 * * 5'

jobs:
  snyk:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t your/image-to-test -f docker/Yii2SecurityTxt/Dockerfile .

      - name: Snyk Docker image scan
        uses: snyk/actions/docker@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # https://github.com/snyk/actions#getting-your-snyk-token
        with:
          image: your/image-to-test
          args: --file=docker/Yii2SecurityTxt/Dockerfile --severity-threshold=medium

      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
